@startuml
'https://plantuml.com/sequence-diagram

Class App {
    Path filepath

}

Class Validator {
    validatePath(Path filePath)
}

Class Reader {
    namesFromFile(File inputFile) : List<List<String>>
}

Class Sorter {
    sortNames(List<List<String>> unsortedNames) : List<List<String>>
}
Class Writer {
    createOutputFile(List<List<String>> sortedNames)
}




App -- Reader
App -- Writer
App -- Sorter
App -- Validator



@enduml